site_name: UVT Scholarly
site_description: Convert WoS and Scopus data to UEFISCDI and CNATDCU criteria verification sheets
site_author: Alex Fikl

repo_url: https://github.com/alexfikl/uvt-scholarly
repo_name: uvt-scholarly

theme:
  name: terminal
  language: en
  palette: light
  features:
    - navigation.side.indexes

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Index: usage.md
    - Web of Science: usage/wos.md
    - Scopus: usage/scopus.md
    - Mathematics: usage/math.md
    - Computer Science: usage/cs.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - name: github
      url: https://github.com/alexfikl/uvt-scholarly
