site_name: UVT Scholarly
site_description: Convert WoS and Scopus data to UEFISCDI and CNATDCU criteria verification sheets
site_author: Alex Fikl

repo_url: https://github.com/alexfikl/uvt-scholarly
repo_name: uvt-scholarly

theme:
  name: terminal
  language: en
  palette: light
  features:
    - navigation.side.indexes

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Index: usage.md
    - Web of Science: usage/wos.md
    - Scopus: usage/scopus.md
    - Mathematics: usage/math.md
    - Computer Science: usage/cs.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
              paths: [src]
              options:
                  show_source: false
                  show_root_heading: false
                  heading_level: 3

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: default
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js

extra:
  social:
    - name: github
      url: https://github.com/alexfikl/uvt-scholarly
