site_name: UVT Scholarly
site_description: Convert WoS and Scopus data to UEFISCDI and CNATDCU criteria verification sheets
site_author: Alex Fikl
site_url: !ENV READTHEDOCS_CANONICAL_URL

repo_url: https://github.com/alexfikl/uvt-scholarly
repo_name: uvt-scholarly

theme:
  name: terminal
  language: en
  palette: light
  features:
    - navigation.side.indexes

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Index: usage.md
    - Web of Science: usage/wos.md
    - Scopus: usage/scopus.md
    - Mathematics: usage/math.md
    - Computer Science: usage/cs.md
  - API Reference: api.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
          python:
              paths: [src]
              inventories:
                - https://docs.python.org/3/objects.inv
              options:
                  show_source: false
                  show_root_heading: false
                  show_root_members_full_path: true
                  heading_level: 3
                  show_bases: true
                  annotations_path: brief
                  show_signature: true
                  show_signature_annotations: true
                  show_signature_type_parameters: true
                  signature_crossrefs: true
                  members_order: source
                  separate_signature: true
                  scoped_crossrefs: true
                  docstring_section_style: list

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.blocks.details:
      types:
        - name: note
          class: 'terminal-alert terminal-alert-primary'
          title: Note
        - name: warning
          class: 'terminal-alert terminal-alert-error'
          title: Warning
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: default
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js

extra_css:
  - css/custom.css

extra:
  social:
    - name: github
      url: https://github.com/alexfikl/uvt-scholarly
